"""Markdown report generator. Reads the audit metrics dict and renders a
self-contained ``report.md`` with embedded plot images and inline tables.

The report is structured to be readable cold by someone reviewing the data
pre-modelling — it deliberately leads with bias / missingness analysis since
those decisions shape the model design more than any single predictor's stats.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd

# ── Helpers ───────────────────────────────────────────────────────────────


def _table(records: list[dict], columns: list[str] | None = None) -> str:
    if not records:
        return "_(none)_"
    df = pd.DataFrame(records)
    if columns:
        df = df[[c for c in columns if c in df.columns]]
    return df.to_markdown(index=False)


def _img(plot_path: Path, plots_dir: Path) -> str:
    if plot_path is None or not plot_path.exists():
        return ""
    rel = plot_path.relative_to(plots_dir.parent)
    return f"![{plot_path.stem}](./{rel})"


def write_report(metrics: dict[str, Any], plots_dir: Path, out_path: Path) -> None:
    schema = metrics["schema"]
    miss = metrics["missingness"]
    tgt = metrics["target"]
    biv = metrics["bivariate"]
    multi = metrics["multicollinearity"]
    out = metrics["outliers"]

    schema_df = pd.DataFrame(schema["schema"])
    n_rows = schema["n_rows"]
    n_cols = schema["n_columns"]

    # Section helpers
    def section(title: str, body: str) -> str:
        return f"\n## {title}\n\n{body}\n"

    # ── Header ─────────────────────────────────────────────────────────────
    header = (
        f"# EDA report — `data/curated/jobs.parquet`\n\n"
        f"_Auto-generated by `eda.audit`. {n_rows:,} rows × {n_cols} columns._\n"
    )

    # ── 1. Headline findings ───────────────────────────────────────────────
    if tgt.get("available"):
        target_md = (
            f"- **Target available**: {tgt['n']:,} rows have `salary_max_usd_yearly` populated "
            f"({tgt['n'] / n_rows * 100:.1f}% of the curated table).\n"
            f"- **Median**: ${tgt['median']:,} / year.  P25/P75: ${tgt['p25']:,} – ${tgt['p75']:,}.\n"
            f"- **Right-skewed**: skew={tgt['skew']:+.2f}, kurtosis={tgt['kurtosis']:+.2f}. "
            f"After log10, skew={tgt['log_skew']:+.2f} (much more symmetric — train on log).\n"
        )
    else:
        target_md = (
            "- ⚠️ **No target rows** — salary mining produced 0 disclosed values. Stop here.\n"
        )

    headline = section(
        "1. Headline",
        target_md
        + "- **Disclosure bias is the dominant data-quality concern** (Section 9).\n"
        + "- **Geographic skew**: ~95% US / ~5% CA. CA model performance will be unreliable on small n.\n"
        + "- **Provider mix**: Greenhouse dominates (~86%); Workday is missing entirely (Phase 4 lift).\n",
    )

    # ── 2. Schema ──────────────────────────────────────────────────────────
    role_counts = schema_df["role"].value_counts().to_dict()
    schema_body = (
        "Columns by role:\n\n"
        + "\n".join(f"- **{role}**: {n}" for role, n in role_counts.items())
        + "\n\n"
        + _img(plots_dir / "01_columns_by_role.png", plots_dir)
        + "\n\n<details>\n<summary>Per-column breakdown (click to expand)</summary>\n\n"
        + schema_df.to_markdown(index=False)
        + "\n\n</details>\n"
    )
    schema_section = section("2. Schema + dtype classification", schema_body)

    # ── 3. Univariate distributions ────────────────────────────────────────
    dist_body = (
        "Continuous predictors:\n\n"
        + _img(plots_dir / "02_continuous_distributions.png", plots_dir)
        + "\n\nCategorical predictors (top 8 levels each):\n\n"
        + _img(plots_dir / "03_categorical_distributions.png", plots_dir)
        + "\n"
    )
    dist_section = section("3. Univariate distributions", dist_body)

    # ── 4. Missingness ─────────────────────────────────────────────────────
    miss_top = pd.Series(miss["missing_rates_pct"]).sort_values(ascending=False).head(15)
    miss_body = (
        "Top 15 most-missing columns:\n\n"
        + miss_top.to_frame("% missing").to_markdown()
        + "\n\n"
        + _img(plots_dir / "05_missingness_rates.png", plots_dir)
        + "\n\n"
        + _img(plots_dir / "04_missingness_matrix.png", plots_dir)
        + "\n\n### MAR / MNAR diagnostics\n\n"
        "Chi-square test: does **missingness in column X** depend on the value of column Y? "
        "If `p_value < 0.05`, missingness is **not random** w.r.t. Y "
        "(i.e. **MAR**, missing-at-random conditional on observed predictors). "
        "If no dependency is detected anywhere we lean towards **MCAR**; "
        "if missingness clearly correlates with values we'd expect it to depend on "
        "(e.g. salary missingness depends on country), that's diagnostic of MAR.\n\n"
        "**Salary disclosure is almost certainly MNAR** — the choice to disclose is made by the "
        "employer and depends on the unobserved actual salary level (companies in highly-paying "
        "buckets disclose less unless legally required). The chi-square table can only show MAR-like "
        "associations with observed columns; the MNAR component remains a modelling concern that "
        "we address via stratified eval and an honest model-card framing.\n\n"
        + _table(miss["mar_signals"], ["missing_column", "vs", "chi2", "p_value", "interpretation"])
    )
    miss_section = section("4. Missingness analysis", miss_body)

    # ── 5. Target deep-dive ────────────────────────────────────────────────
    if tgt.get("available"):
        target_body = (
            f"`{('salary_max_usd_yearly')}`: n={tgt['n']:,}, "
            f"mean ${tgt['mean']:,}, median ${tgt['median']:,}, std ${tgt['std']:,}.\n\n"
            f"- Percentiles: P10 ${tgt['p10']:,}, P25 ${tgt['p25']:,}, P75 ${tgt['p75']:,}, "
            f"P90 ${tgt['p90']:,}, P99 ${tgt['p99']:,}\n"
            f"- Skew: raw {tgt['skew']:+.2f} → log {tgt['log_skew']:+.2f}\n"
            f"- Kurtosis: raw {tgt['kurtosis']:+.2f} → log {tgt['log_kurtosis']:+.2f}\n\n"
            "**Recommendation**: train the regressor on `log10(target)`; report MAE in USD via "
            "back-transform. Symmetric residuals + better-behaved tails for tree-based models.\n\n"
            + _img(plots_dir / "06_target_distribution.png", plots_dir)
            + "\n\nStratified by country / source / role / seniority:\n\n"
            + _img(plots_dir / "07_target_by_strata.png", plots_dir)
            + "\n"
        )
    else:
        target_body = "_target unavailable_"
    target_section = section("5. Target deep-dive", target_body)

    # ── 6. Bivariate ───────────────────────────────────────────────────────
    biv_body = (
        "**Continuous predictors vs target** (Pearson + Spearman correlation, "
        "ranked by |Spearman|):\n\n"
        + _table(biv["continuous"], ["predictor", "n", "pearson", "spearman"])
        + "\n\n**Categorical predictors vs target** (one-way ANOVA F-test "
        "across groups; small p-value ⇒ group means differ):\n\n"
        + _table(biv["categorical"], ["predictor", "n", "groups", "anova_f", "p_value"])
        + "\n\n**Boolean predictors vs target** (Welch t-test on yes/no medians):\n\n"
        + _table(
            biv["boolean"],
            ["predictor", "n_yes", "n_no", "median_yes", "median_no", "t_stat", "p_value"],
        )
    )
    biv_section = section("6. Bivariate (target vs predictors)", biv_body)

    # ── 7. Multicollinearity ───────────────────────────────────────────────
    multi_body = (
        "VIF on continuous predictors (rule of thumb: VIF > 5 ⇒ moderate, > 10 ⇒ severe "
        "multicollinearity):\n\n"
        + _table(multi["vif"], ["predictor", "vif"])
        + f"\n\n**Condition number** of the design matrix (1 + continuous block): "
        f"`{multi['condition_number']}`. > 30 hints at multicollinearity; > 100 is severe.\n\n"
        + _img(plots_dir / "08_correlation_heatmap.png", plots_dir)
        + "\n\nNote: ordinal / nominal predictors must be encoded before VIF is meaningful for them. "
        "We'll redo this on the full one-hot design matrix in the modelling step.\n"
    )
    multi_section = section("7. Multicollinearity", multi_body)

    # ── 8. Outliers ────────────────────────────────────────────────────────
    out_records = [{"predictor": k, **v} for k, v in out.items() if isinstance(v, dict)]
    out_body = (
        _table(
            out_records,
            [
                "predictor",
                "n",
                "min",
                "max",
                "iqr_low_fence",
                "iqr_high_fence",
                "n_iqr_outliers",
                "n_z_above_3",
            ],
        )
        + "\n\n"
        + _img(plots_dir / "09_target_outliers.png", plots_dir)
        + "\n\n**Sanity checks** worth performing manually before training:\n"
        "- Hourly-rate postings (salary_period=`hour`) should annualize plausibly. We multiply by 2080 "
        "(40 h × 52 wk) which biases part-time gigs upward; tree-based models should handle this.\n"
        "- Anything below ~$30k/yr USD-equivalent is likely a stipend or part-time misclassification.\n"
        "- Anything above ~$1M/yr is likely a typo, total-comp including unvested equity, or a "
        "C-suite role; consider winsorizing at the 99.5th percentile.\n"
    )
    out_section = section("8. Outliers", out_body)

    # ── 9. Bias + transformation recs ──────────────────────────────────────
    bias_body = (
        "### Selection / disclosure bias (the big one)\n\n"
        "Only ~50% of NA tech postings disclose salary — and disclosure is **not random**:\n\n"
        "- **Geographic mandate**: California, NYC, Washington, Colorado, Connecticut, "
        "Maryland, Illinois and Hawaii (US) plus Ontario, BC and PEI (CA) require disclosure on "
        "postings in their jurisdictions. Roles primarily based outside these are systematically "
        "less likely to disclose ⇒ *region-conditional MAR*.\n"
        "- **Company policy**: high-disclosure companies (Stripe, Anduril, Cohere, Anthropic) over-"
        "represent the disclosed sample; low-disclosure companies (most defense / non-listed) are "
        "under-represented.\n"
        "- **Salary-conditional self-selection (MNAR)**: within a non-mandated jurisdiction, "
        "companies offering above-market or below-market pay disclose at different rates than the "
        "modal mid-pay company. We can't observe this directly.\n\n"
        "**Implications for modelling**:\n"
        "1. The model predicts salary *as a disclosing company in our corpus would price the role*. "
        "State this explicitly in the model card.\n"
        "2. Stratified eval: report MAE / MAPE separately by country and source so the residual "
        "bias inside the disclosing pool is visible.\n"
        "3. Consider a 2-stage model later: P(disclosed | features) + E[salary | disclosed, features]. "
        "Phase 2 ships only the second stage; Phase 4+ can revisit.\n\n"
        "### Omitted-variable risks\n\n"
        "- **No company-size / valuation feature**: salary correlates strongly with whether a company "
        "is post-IPO, late-stage private, or pre-Series-B. We can't infer this from the ATS payload, "
        "so the model implicitly attributes that variation to `company_slug` (high-cardinality, leaky).\n"
        "- **No 'years since founded' / 'industry vertical' beyond what title regex catches**.\n"
        "- **No total-comp breakdown** (base vs equity vs bonus). Some Bay Area roles disclose only "
        "base — others disclose total. We can't distinguish without text mining the description.\n\n"
        "### Transformation recommendations (for Step 3 modelling)\n\n"
        "| Predictor | Transform |\n"
        "|---|---|\n"
        "| `salary_max_usd_yearly` (target) | `log10` (raw is right-skewed) |\n"
        "| `country` | one-hot (only 2 levels — `US`, `CA`) |\n"
        "| `region` (~30 distinct values) | target encode with k-fold leakage protection |\n"
        "| `source` | one-hot |\n"
        "| `role_family_extracted` (9 levels) | one-hot |\n"
        "| `seniority_extracted` (9 ordinal levels) | integer encode (preserves order) |\n"
        "| `min_education` (5 ordinal levels) | integer encode |\n"
        "| `min_years_experience` | keep raw + add `is_missing` indicator |\n"
        "| `remote_policy` | one-hot, with `<missing>` as its own level |\n"
        "| Boolean fields with `boolean` dtype | impute False → 0; missingness mask separately |\n"
        "| `tech_stack` (list of str) | top-N indicator columns OR count |\n"
        "| `posted_at` | derive `days_since_posted`, drop the raw timestamp |\n"
        "| `company_slug` | **don't** one-hot directly (~65 levels, leaky); target-encode with k-fold |\n"
        "\n### Multicollinearity hot spots\n\n"
        "Already-known sources of redundancy we'll guard against:\n"
        "- `salary_min_usd_yearly` vs `salary_max_usd_yearly` (corr ≈ 0.95) — drop min from the input.\n"
        "- `min_years_experience` vs `seniority_extracted` (likely Spearman > 0.5) — keep both, "
        "tree-based models handle the redundancy fine.\n"
        "- `manager_role` and `seniority_extracted` (manager/director appear in both) — overlap "
        "expected; we'll re-check VIF on the full encoded matrix.\n"
    )
    bias_section = section("9. Bias, omitted-variable risk, transformation recs", bias_body)

    # ── 10. Modelling implications ─────────────────────────────────────────
    next_steps = section(
        "10. What this means for Step 3 (modelling)",
        "1. **Train target**: `log10(salary_max_usd_yearly)` on the disclosed subset.\n"
        "2. **Stratified eval**: report MAE / MAPE / R² broken out by `country` and `source`.\n"
        "3. **Honest framing in the model card**: the model predicts salary as priced by "
        "disclosing employers in this corpus — _not_ ground truth.\n"
        "4. **Drop**: `salary_min_*` from inputs (information leak). `id`, `url`, `description_md` "
        "are not used as tabular features (description goes through bge-m3 in Phase 5; for Phase 2's "
        "first regressor we keep tabular only).\n"
        "5. **Handle**: high-cardinality `region` and `company_slug` via target encoding with "
        "k-fold leakage protection.\n"
        "6. **Don't use** anything still 0%-fill (industry_experience, team_or_department, "
        "direct_reports_count, max_years_experience). Revisit in Phase 4+ when LLM tier is enabled "
        "or DeBERTa classifiers replace the title-regex heuristics.\n",
    )

    body = "\n".join(
        [
            header,
            headline,
            schema_section,
            dist_section,
            miss_section,
            target_section,
            biv_section,
            multi_section,
            out_section,
            bias_section,
            next_steps,
        ]
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(body)
